add_unit_test(
	test01
	tests/test_error.c
	src/err/error.c
)
add_unit_test(
	test02
	tests/pcunit_main.c
	tests/test_pcunit_example.c
	tests/test_pcunit_mempool.c
	tests/test_pcunit_tsk.c
	tests/test_pcunit_itc.c
	src/err/error.c
	src/tsk/tsk.c
    src/mempool.c
    src/itc/itc.c
)
add_unit_test(
	test03
	tests/test_list.c
	src/list.c
)
add_unit_test(
	test04
	tests/test_tsk.c
	src/tsk/tsk.c
	src/err/error.c
)
